credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: '$2b$12$9DbZ5...REPLACE_WITH_HASH'
    admin:
      email: admin@example.com
      name: Admin
      password: '$2b$12$Pp3Qz...REPLACE_WITH_HASH'

cookie:
  name: smartshield_cookie
  key: some_random_secret_key_12345
  expiry_days: 30
